/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
      colors:{
        lamaSky:"#C3EBFA",
        lamaSkyLight:"#EDF9FD",
        lamaPruple:"#CFCEFF",
        lamaPrupleLight:"#F1F0FF",
        lamaYellow:"#FAE27C",
        lamaYellowLight:"#FEFCEB",
        lamaLightGray:"#D3D3D3",
        lamaSilver:"#C0C0C0",
        lamaDarkGray:"#A9A9A9",
        lamaGray:"#808080",
        lamaDimGray:"#696969",
        lamaLightSlateGray:"#778899",
        lamaBlack:"#000000",
        lamaLightGray:"#D3D3D3",
        // Green Color
        lamaGreen:"#00FF00",
        lamaGreenLight:"#90EE90",
        lamaGreenPale:"#98FB98",
        lamaGreenDark:"#008000",
        lamaGreenLightDark:"#006400",
        lamaGreenLightPale:"#20B2AA",
        lamaGreenLightLight:"#7FFFD4",
        // Blue Color
        lamaBlue:"#0000FF",
        lamaBlueLight:"#ADD8E6",
        lamaBluePale:"#B0E0E6",
        lamaBlueDark:"#00008B",
        lamaBlueLightDark:"#000080",
        lamaBlueLightPale:"#87CEEB",
        lamaBlueLightLight:"#87CEFA",
        // Red Color
        lamaRed:"#FF0000",
        lamaRedLight:"#FFA07A",
        lamaRedPale:"#FA8072",
        lamaRedDark:"#8B0000",
        lamaRedLightDark:"#800000",
        lamaRedLightPale:"#CD5C5C",
        lamaRedLightLight:"#F08080",
        // Yellow Color
        lamaYellow:"#FFFF00",
        lamaYellowLight:"#FFD700",
        lamaYellowPale:"#EEE8AA",
        lamaYellowDark:"#BDB76B",
        lamaYellowLightDark:"#ADFF2F",
        lamaYellowLightPale:"#9ACD32",
        lamaYellowLightLight:"#556B2F",
        // Purple Color
        lamaPurple:"#800080",
        lamaPurpleLight:"#BA55D3",
        lamaPurplePale:"#9370DB",
        lamaPurpleDark:"#4B0082",
        lamaPurpleLightDark:"#9932CC",
        lamaPurpleLightPale:"#8A2BE2",
        lamaPurpleLightLight:"#9400D3",
        // Orange Color
        lamaOrange:"#FFA500",
        lamaOrangeLight:"#FF8C00",
        lamaOrangePale:"#FF7F50",
        lamaOrangeDark:"#FF6347",
        lamaOrangeLightDark:"#FF4500",
        lamaOrangeLightPale:"#FFD700",
        lamaOrangeLightLight:"#FFA07A",
        // Brown Color
        lamaBrown:"#A52A2A",
        lamaBrownLight:"#D2691E",
        lamaBrownPale:"#CD853F",
        lamaBrownDark:"#8B4513",
        lamaBrownLightDark:"#A0522D",
        lamaBrownLightPale:"#DEB887",
        lamaBrownLightLight:"#F4A460",
        // White Color
        lamaWhite:"#FFFFFF",
        lamaWhiteLight:"#F0F8FF",
        lamaWhitePale:"#FFFAF0",
        lamaWhiteDark:"#F8F8FF",
        lamaWhiteLightDark:"#F5F5F5",
        lamaWhiteLightPale:"#F5FFFA",
        lamaWhiteLightLight:"#F0FFFF",
        // Black Color
        lamaBlack:"#000000",
        lamaBlackLight:"#2F4F4F",
        lamaBlackPale:"#708090",
        lamaBlackDark:"#696969",
        lamaBlackLightDark:"#708090",
        lamaBlackLightPale:"#778899",
        lamaBlackLightLight:"#B0C4DE",
        // Gray Color
        lamaGray:"#808080",
        lamaGrayLight:"#A9A9A9",
        lamaGrayPale:"#D3D3D3",
        lamaGrayDark:"#696969",
        lamaGrayLightDark:"#778899",
        lamaGrayLightPale:"#708090",
        lamaGrayLightLight:"#B0C4DE",
        // Silver Color
        lamaSilver:"#C0C0C0",
        lamaSilverLight:"#DCDCDC",
        lamaSilverPale:"#F0F0F0",
        lamaSilverDark:"#A9A9A9",
        lamaSilverLightDark:"#C0C0C0",
        lamaSilverLightPale:"#D3D3D3",
        lamaSilverLightLight:"#DCDCDC",
        // Maroon Color
        lamaMaroon:"#800000",
        lamaMaroonLight:"#B03060",
        lamaMaroonPale:"#C71585",
        lamaMaroonDark:"#8B0000",
        lamaMaroonLightDark:"#800000",
        lamaMaroonLightPale:"#DB7093",
        lamaMaroonLightLight:"#CD5C5C",
      }
    },
  },
  plugins: [],
};
